name: Kernel Build

on:
  push:
    branches: [build ]
    
jobs:

  build:

    runs-on: ubuntu-latest


    steps:

    - uses: actions/checkout@v2

    - name: Cache Toolchain
      id: cache-toolchain
      uses: actions/cache@v1
      with:
        path: ~/toolchains
        key: ${{ runner.os }}-tc

    - name: Setup the toolchain
      if: steps.cache-toolchain.outputs.cache-hit != 'true'
      run: bash ./builder toolchain

    - name: We'll just modify this later
      run: bash ./kangronos.sh build
      
    - name: Upload boot.img and zip
      uses: actions/upload-artifact@v2
      with:
       name: Kangronos
       path:  Cronos/Product/*
    
     
   
